language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
deploy:
  provider: pypi
  user: maxhumber
  password: $PYPI_PASSWORD

install:
  - "pip install -e ."
  - "pip install pytest"

script:
  - pytest tests/
